[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
evalexpr = "12.0.1"
rayon = "1.10.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3